apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-8fw5hy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-8fw5hy
  namespace: my-nginx-8fw5hy
  labels:
    name: nginx-8fw5hy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-8fw5hy
  template:
    metadata:
      namespace: my-nginx-8fw5hy
      labels:
        name: nginx-8fw5hy
    spec:
      containers:
      - name: nginx-8fw5hy
        image: nginx
        ports:
        - containerPort: 80

